FROM node:alpine3.21
#  Set The working directory
WORKDIR /app
#  Copy both package.json and package-lock.json
COPY package.json .

# install dependencies
RUN npm install

# Copy the rest of the files
COPY . .
# Expose the port the app runs in
EXPOSE 3000
# Start the application
CMD ["npm", "start"]