# Base Image
FROM node:20-alpine AS base

## Set working directory
WORKDIR /app

## Install build dependencies required for canvas
RUN apk add --no-cache \
      python3 \
      make \
      g++ \
      cairo-dev \
      jpeg-dev \
      pango-dev \
      giflib-dev \
      pixman-dev

## Install dependencies
COPY package*.json ./
RUN npm install

# copy all files
COPY . .

# Runtime environment
FROM node:20-alpine AS runtime

# Install only runtime dependencies for canvas
RUN apk add --no-cache \
      cairo \
      jpeg \
      pango \
      giflib \
      pixman

# set working directory
WORKDIR /app

# Copy only the production dependencies from the builder stage
COPY --from=base /app/node_modules ./node_modules

# Copy only the necessary files from the builder stage
COPY --from=base /app ./

# Security best practice: Switch to a non-root user
RUN adduser -D backendUser
USER backendUser

# Expose the port the app runs on
EXPOSE 3002
# 5️⃣ Set environment (optional)
ENV NODE_ENV=production

# Start the application
CMD ["npm", "start"]


# // If need to use bind mount for development, uncomment below
# # Use a volume to persist node_modules
VOLUME [ "/app/node_modules" ]
# docker run --mount type=bind,src=/mnt/sda1/client-project/SensTailor/ai-calculator-backend-app,dst=/app --name tailor-backend-v2 -d -p 3002:3002 senstailor-backend:v1 